### ISSUE TITLE
README errors corrected

### ISSUE THREAD

**Issue by InFerYes** [PowaBanga/DDaynormandyFPS#10]
DDay: Normandy FPS
==================
This is the complete source of _DDay: Normandy FPS_. It is a Quake II total conversion.

_DDay: Normandy FPS_ is an opensource game which was abandoned by its developers, which is now solely developed by its fans.

If you like it, please just share it and play it with your friends.

How to install:
---------------
You can download [the latest release](https://github.com/PowaBanga/DDaynormandyFPS/releases/latest) (don't forget to install dependency) but if you prefer to compile the game, have a look at the [INSTALL](INSTALL.md) file.

How to play:
------------
 * `ESCAPE` -> Main menu
 * `[`,`]`,`PAGEDOWN/UP` -> go up/down in game menu
 * `A`,`S`,`D`,`W` or `ARROWS`  -> movements
 * `Q` -> take items
 * `SPACE` -> Jump
 * `CTRL` or `C` -> down-crouch
 * `Left click` -> shoot
 * `Right click` -> use weapon (position to aim)
 * `R` or `Middle click` -> reload

Links:
------
 * [Development site](http://ddaydev.com/)
 * [French site](http://ddaynormandy.keumforum.com/)
 * [Chilean site (spanish)](http://ddaychile.com/)
 * [Facebook page](https://www.facebook.com/ddaynormandyquake2)
 * [Find players on facebook](https://www.facebook.com/groups/ddaynormandy)
 * [How to contribue](https://github.com/PowaBanga/DDaynormandyFPS/wiki/How-to-contribue)
 * [Last realese](https://github.com/PowaBanga/DDaynormandyFPS/releases/latest)
 
_*IRC:*_ #ddayhome on irc.quakenet.org 

Screenshots:
-------
![](https://holysh1t.net/dday/dynamic.ddaynormandy.com/dday/include/images/quake2max092.jpg)

![Omaha Beach](https://holysh1t.net/dday/dynamic.ddaynormandy.com/dday/include/images/quake2max089.jpg)
![DDay2 map](https://holysh1t.net/dday/dynamic.ddaynormandy.com/dday/include/images/quake2max039.jpg)

Thanks:
-------

Thanks to Skuller for the Q2pro engine. Thanks to Fafner for his DDayDev website, and all his contributions to improve the game. Thanks to Dirk who improves the code too, and helps me to understand how the game works. Thank you to all those who supported me in my approach and supported me for everything I created for this game. Thanks to Vipersoft who published this game as opensource. Thanks to all guys and players who created some models, pictures, maps to improve the game and who shared them. And at last, thanks to all players who promote this game and who never stop playing it.

English is not my native language, so I am sorry if my wording is not perfect. ;)

**Comment by InFerYes** [comment]
The screenshots should actually show up instead of being links, but I don't know why Github doesn't do it.

**Comment by PowaBanga** [comment]
you really should use merge request, i totaly forgot this post.
I see correctly the screenshots, maybe is it from your browser ?

**Comment by InFerYes** [comment]
This is from 2018 lol. The screenshots show now, I didn't know how to do a pull request back then.

**Comment by PowaBanga** [comment]
ok, i have to teach that to you :)
